appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
  - key: ENV_VAR_ONE
    value: "valueone"
  - key: ENV_VAR_TWO
    value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP